#!/bin/bash

DOTFILES=$HOME/.dotfiles

GIT_REPO=$1

git clone ${GIT_REPO:="/Users/lucastorri/Projects/dotfiles-control"} $DOTFILES

echo "export PATH=\$PATH:$DOTFILES/bin" >> $HOME/.bashrc

if [ ! -d $DOTFILES/dotfiles ]
then
  DOTFILES_REPO=$DOTFILES/dotfiles
  mkdir $DOTFILES_REPO
fi

if [ "$1" == "" ]
then
  cd $DOTFILES
  git remote rm origin
  read -p "Which is your repo? " GIT_REPO
  git remote add origin "$GIT_REPO"
  git push -u origin master
fi

cd $DOTFILES
git remote add dotfiles git://github.com/lucastorri/dotfiles.git

for FILE in `ls -A $DOTFILES/dotfiles`
do
  ln -s $DOTFILES/dotfiles/$FILE $HOME
done

cd $DOTFILES
# fix url: echo "bash < <(curl -s $GIT_REPO)" > README
