#!/bin/bash

ORIGINAL_REPO="git@github.com:lucastorri/dotfiles-control.git"

GIT_REPO=$ORIGINAL_REPO

DOTFILES=$HOME/.dotfiles

git clone $GIT_REPO $DOTFILES

echo "export PATH=\$PATH:$DOTFILES/bin" >> $HOME/.bashrc

if [ ! -d $DOTFILES/dotfiles ]
then
  mkdir $DOTFILES/dotfiles
fi

if [ "$GIT_REPO" == "$ORIGINAL_REPO" ]
then
  cd $DOTFILES
  read -p "Which is your repo? " GIT_REPO
  cat install | sed "s|GIT_REPO=\$ORIGINAL_REPO|GIT_REPO=$GIT_REPO|g" > install
  git remote rm origin
  git remote add origin "$GIT_REPO"
  git push -u origin master
  git remote add dotfiles $ORIGINAL_REPO
fi

for FILE in `ls -A $DOTFILES/dotfiles`
do
  ln -s $DOTFILES/dotfiles/$FILE $HOME
done

# fix url: echo "bash < <(curl -s $GIT_REPO)" > README
