#!/bin/bash

DOTFILES=$HOME/.dotfiles

GIT_REPO=$1

git clone ${GIT_REPO:="git@github.com:lucastorri/dotfiles-control.git"} $DOTFILES

echo "export PATH=\$PATH:$DOTFILES/bin" >> $HOME/.bashrc

if [ ! -d $DOTFILES/dotfiles ]
then
  DOTFILES_REPO=$DOTFILES/dotfiles
  mkdir $DOTFILES_REPO
fi

if [ "$GIT_REPO" == "" ]
then
  cd $DOTFILES
  git remote rm origin
  echo "Which is your repo?"
  read GIT_REPO
  git remote add origin "$GIT_REPO"
  git push -u origin master
fi

cd $DOTFILES
echo "bash < <(curl -s $GIT_REPO)"
